package com.dhurd.club.login.core;

import javax.swing.JPanel;

public final class SetupVisualPanel3 extends JPanel {
    private String password;
    private String tempPass;
    private boolean hidden = true;

    public SetupVisualPanel3() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Finish Setup";
    }
    
    void setUsername(String name) {
        managerNameLabel.setText(name);
    }
    
    void setPassword(String password) {
        this.password = password;
        tempPass = "";
        hidden = true;
        for (int i=0; i< password.length(); i++) {
            tempPass = tempPass + "*";
        }
        managerPasswordLabel.setText(tempPass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        managerNameLabel = new javax.swing.JLabel();
        managerPasswordLabel = new javax.swing.JLabel();
        showPasswordButton = new javax.swing.JButton();

        jScrollPane1.setBorder(null);

        infoTextArea.setEditable(false);
        infoTextArea.setBackground(new java.awt.Color(240, 240, 240));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setText(org.openide.util.NbBundle.getMessage(SetupVisualPanel3.class, "SetupVisualPanel3.infoTextArea.text")); // NOI18N
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setBorder(null);
        jScrollPane1.setViewportView(infoTextArea);

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(SetupVisualPanel3.class, "SetupVisualPanel3.nameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, org.openide.util.NbBundle.getMessage(SetupVisualPanel3.class, "SetupVisualPanel3.passwordLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(managerNameLabel, org.openide.util.NbBundle.getMessage(SetupVisualPanel3.class, "SetupVisualPanel3.managerNameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(managerPasswordLabel, org.openide.util.NbBundle.getMessage(SetupVisualPanel3.class, "SetupVisualPanel3.managerPasswordLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(showPasswordButton, org.openide.util.NbBundle.getMessage(SetupVisualPanel3.class, "SetupVisualPanel3.showPasswordButton.text")); // NOI18N
        showPasswordButton.setMaximumSize(new java.awt.Dimension(125, 23));
        showPasswordButton.setMinimumSize(new java.awt.Dimension(125, 23));
        showPasswordButton.setPreferredSize(new java.awt.Dimension(125, 23));
        showPasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordLabel)
                                .addGap(18, 18, 18)
                                .addComponent(managerPasswordLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(managerNameLabel))
                            .addComponent(showPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(managerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(managerPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPasswordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordButtonActionPerformed
        if (hidden) {
            managerPasswordLabel.setText(password);
            showPasswordButton.setText("Hide Password");
            hidden = false;
        } else {
            managerPasswordLabel.setText(tempPass);
            showPasswordButton.setText("Show Password");
            hidden = true;
        }
    }//GEN-LAST:event_showPasswordButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel managerNameLabel;
    private javax.swing.JLabel managerPasswordLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton showPasswordButton;
    // End of variables declaration//GEN-END:variables
}
