package com.dhurd.club.login.core;

import javax.swing.JPanel;

public final class SetupVisualPanel2 extends JPanel {
    SetupWizardPanel2 wizPanel;

    public SetupVisualPanel2(SetupWizardPanel2 wizPanel) {
        initComponents();
        this.wizPanel = wizPanel;
    }

    @Override
    public String getName() {
        return "Setting up Manager Account";
    }
    
    String getUsername() {
        return nameTextField.getText();
    }
    
    String getPassword() {
        return new String(passwordField.getPassword());
    }
    
    String getVerifyPassword() {
        return new String(verifyPasswordField.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        nameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        verifyPasswordField = new javax.swing.JPasswordField();

        jScrollPane1.setBorder(null);

        infoTextArea.setEditable(false);
        infoTextArea.setBackground(new java.awt.Color(240, 240, 240));
        infoTextArea.setColumns(20);
        infoTextArea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        infoTextArea.setLineWrap(true);
        infoTextArea.setRows(5);
        infoTextArea.setText(org.openide.util.NbBundle.getMessage(SetupVisualPanel2.class, "SetupVisualPanel2.infoTextArea.text")); // NOI18N
        infoTextArea.setWrapStyleWord(true);
        infoTextArea.setBorder(null);
        jScrollPane1.setViewportView(infoTextArea);

        org.openide.awt.Mnemonics.setLocalizedText(nameLabel, org.openide.util.NbBundle.getMessage(SetupVisualPanel2.class, "SetupVisualPanel2.nameLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(passwordLabel, org.openide.util.NbBundle.getMessage(SetupVisualPanel2.class, "SetupVisualPanel2.passwordLabel.text")); // NOI18N

        nameTextField.setText(org.openide.util.NbBundle.getMessage(SetupVisualPanel2.class, "SetupVisualPanel2.nameTextField.text")); // NOI18N
        nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextFieldKeyReleased(evt);
            }
        });

        passwordField.setText(org.openide.util.NbBundle.getMessage(SetupVisualPanel2.class, "SetupVisualPanel2.passwordField.text")); // NOI18N
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SetupVisualPanel2.class, "SetupVisualPanel2.jLabel1.text")); // NOI18N

        verifyPasswordField.setText(org.openide.util.NbBundle.getMessage(SetupVisualPanel2.class, "SetupVisualPanel2.verifyPasswordField.text")); // NOI18N
        verifyPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                verifyPasswordFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(passwordLabel)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verifyPasswordField)
                            .addComponent(passwordField)
                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(verifyPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextFieldKeyReleased
        if(!getUsername().isEmpty()
                && !getPassword().isEmpty()
                && !getVerifyPassword().isEmpty()) {
            wizPanel.setNextButtonEnabled(true);
        } else {
            wizPanel.setNextButtonEnabled(false);
        }
    }//GEN-LAST:event_nameTextFieldKeyReleased

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
        if(!getUsername().isEmpty()
                && !getPassword().isEmpty()
                && !getVerifyPassword().isEmpty()) {
            wizPanel.setNextButtonEnabled(true);
        } else {
            wizPanel.setNextButtonEnabled(false);
        }
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void verifyPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifyPasswordFieldKeyReleased
        if(!getUsername().isEmpty()
                && !getPassword().isEmpty()
                && !getVerifyPassword().isEmpty()) {
            wizPanel.setNextButtonEnabled(true);
        } else {
            wizPanel.setNextButtonEnabled(false);
        }
    }//GEN-LAST:event_verifyPasswordFieldKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField verifyPasswordField;
    // End of variables declaration//GEN-END:variables
}
